### ISSUE TITLE
new

### ISSUE THREAD

**Issue by aaa34169** [cadop/pyCGM#1]
Hi, 
I come across your dev. 
I dont know if your projet is still in progress. 
If yes, i can say you i have a full-python code of the Vicon Plugin Gait Model.  
Both kinematics and  kinetics, were compared  and verfified. 

feel free to contact me if you were inerested in. 

cheers

fabien

**Comment by cadop** [comment]
Hi Fabien,

Sure I would be interested in seeing your code.  How did you verify it?  We
have verified our code against Vicon Nexus already, so would be intersted
to see your results as well.

Thanks,

Mat

**Comment by syeon71** [comment]
Oh.....dang.....he even has a Kinetics code?! Should we collaborate with him? 

나의 iPhone에서 보냄

2016. 7. 9. 오전 7:41 Fabien Leboeuf <notifications@github.com> 작성:
