### ISSUE TITLE
Many functions are missing Docstrings

### ISSUE THREAD

**Issue by moppr** [cadop/pyCGM#12]
The following functions from each of these files need to have docstrings written for them in Numpy format:

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/clusterCalc.py

- [ ] normalize
- [ ] printMat
- [ ] getMarkerLocation
- [ ] getStaticTransform
- [ ] targetName
- [ ] target_dict
- [ ] segment_dict

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/Pipelines.py

- [ ] butterFilter
- [ ] filt
- [ ] transform_from_static
- [ ] transform_from_mov
- [ ] segmentFinder
- [ ] rigid_fill

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmCalc.py

- [ ] calcKinetics
- [ ] calcAngles
- [ ] Calc
- [ ] calcFrames

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmClusters.py

- [ ] calcFramesClusters

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmKinetics.py

- [ ] getKinetics

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmIO.py

- [ ] createMotionDataDict
- [ ] splitMotionDataDict
- [ ] createVskDataDict
- [ ] splitVskDataDict
- [ ] markerKeys
- [ ] loadEZC3D
- [ ] loadC3D
- [ ] loadCSV
- [ ] loadData
- [ ] dataAsArray
- [ ] dataAsDict
- [ ] writeKinetics
- [ ] writeResult
- [ ] smKeys
- [ ] loadVSK
- [ ] splitDataDict
- [ ] combineDataDict
- [ ] make_sure_path_exists

**Comment by niravkin** [comment]
I would like to work on writing these docstrings.
