### ISSUE TITLE
No Unit Tests have been implemented

### ISSUE THREAD

**Issue by moppr** [cadop/pyCGM#14]
The following functions from each of these files need to unit tests written for them:

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/clusterCalc.py

- [ ] normalize
- [ ] printMat
- [ ] getMarkerLocation
- [ ] getStaticTransform
- [ ] targetName
- [ ] target_dict
- [ ] segment_dict

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/Pipelines.py

- [ ] butterFilter
- [ ] filt
- [ ] prep
- [ ] clearMarker
- [ ] filtering
- [ ] transform_from_static
- [ ] transform_from_mov
- [ ] segmentFinder
- [ ] rigid_fill

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pyCGM.py

- [ ] pelvisJointCenter
- [ ] hipJointCenter
- [ ] hipAxisCenter
- [ ] kneeJointCenter
- [ ] ankleJointCenter
- [ ] footJointCenter
- [ ] headJC
- [ ] thoraxJC
- [ ] findwandmarker
- [ ] findshoulderJC
- [ ] shoulderAxisCalc
- [ ] elbowJointCenter
- [ ] wristJointCenter
- [ ] handJointCenter
- [ ] findJointC
- [ ] cross
- [ ] getPelangle
- [ ] getHeadangle
- [ ] getangle_sho
- [ ] getangle_spi
- [ ] getangle
- [ ] norm2d
- [ ] norm3d
- [ ] normDiv
- [ ] matrixmult 
- [ ] rotmat
- [ ] JointAngleCalc

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmCalc.py

- [ ] calcKinetics
- [ ] calcAngles
- [ ] Calc
- [ ] calcFrames

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmClusters.py

- [ ] calcFramesClusters

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmIO.py

- [ ] createMotionDataDict
- [ ] splitMotionDataDict
- [ ] createVskDataDict
- [ ] splitVskDataDict
- [ ] markerKeys
- [ ] loadEZC3D
- [ ] loadC3D
- [ ] loadCSV
- [ ] loadData
- [ ] dataAsArray
- [ ] dataAsDict
- [ ] writeKinetics
- [ ] writeResult
- [ ] smKeys
- [ ] loadVSK
- [ ] splitDataDict
- [ ] combineDataDict
- [ ] make_sure_path_exists

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmKinetics.py

- [ ] f
- [ ] dot
- [ ] length
- [ ] vector
- [ ] unit
- [ ] distance
- [ ] scale
- [ ] add
- [ ] pnt2line
- [ ] findL5_Pelvis
- [ ] findL5_Thorax
- [ ] getKinetics

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmStatic.py

- [ ] rotmat
- [ ] getDist
- [ ] getStatic
- [ ] average
- [ ] IADcalculation
- [ ] staticCalculationHead
- [ ] headoffCalc
- [ ] staticCalculation
- [ ] pelvisJointCenter
- [ ] hipJointCenter
- [ ] hipAxisCenter
- [ ] kneeJointCenter
- [ ] ankleJointCenter
- [ ] footJointCenter
- [ ] headJC
- [ ] uncorrect_footaxis
- [ ] rotaxis_footflat
- [ ] rotaxis_nonfootflat
- [ ] getankleangle
- [ ] findJointC
- [ ] norm2d
- [ ] norm3d
- [ ] normDiv
- [ ] matrixmult 
- [ ] cross

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgm_embed.py

- [ ] getfilenames
- [ ] loadData
- [ ] main

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pyCGM_Helpers.py

- [ ] getfilenames

**Comment by thepeytongreen** [comment]
I would like to work on creating these unit tests
