### ISSUE TITLE
Relative imports fail when using doctest in docstrings

### ISSUE THREAD

**Issue by GVeras** [cadop/pyCGM#18]
After having pip install the pyCGM module, a few of the relative imports do not work with doctests in docstrings. 

For a example, a successful import in a doctest:
```
"""
>>>  from pycgmKinetics import unit
"""
if __name__ == "__main__":
    import doctest
    doctest.testmod()
```

Will yield the result:

> Trying:
>     from pycgmKinetics import unit
> Expecting nothing
> Test passed.
> 

While an doctest like this :
```
"""
>>> from pyCGM import cross
"""

if __name__ == "__main__":
    import doctest
    doctest.testmod()
```
Yields the error:
> Failed example:
>     from pyCGM import cross
> Exception raised:
>     Traceback (most recent call last):
>       File "C:\Users\GabrielVeras\.windows-build-tools\python27\lib\doctest.py", line 1315, in __run
>         compileflags, 1) in test.globs
>       File "<doctest test file[0]>", line 1, in <module>
>         from pyCGM import cross
>       File "pyCGM.py", line 30, in <module>
>         from .pycgmIO import *
>     ValueError: Attempted relative import in non-package
>   ***Test Failed*** 1 failures.

In general, attempting to import from pyCGM or importing any method from the pyCGM file results in the same error.

**Comment by cadop** [comment]
Its not clear to me now that this is just a relative imports issue with the module or with doctest.

**Comment by GVeras** [comment]
I believe it is more of a issue with the module because running pyCGM.py with a debugger recreates the error, and running the line
`import pyCGM` from an external python file in the same directory recreates the error.

The error of course being `ImportError: attempted relative import with no known parent package` from the `from .pycgmIO import *` line in pyCGM_Single/pyCGM.py

**Comment by cadop** [comment]
This is caused by running doctest on a file of a module instead of the module.
