### ISSUE TITLE
Support for old c3d formats (ex. DEC integer format)

### ISSUE THREAD

**Issue by lasagnaphil** [cadop/pyCGM#2]
Maybe it would be great if the old c3d loader can be replaced by ezc3d (https://github.com/pyomeca/ezc3d), as it has support for a wider range of formats.

**Comment by cadop** [comment]
https://github.com/cadop/pyCGM/commit/6bf768b06fd8b0930a48669e9ce8f66c4783777c

**Comment by lasagnaphil** [comment]
Thank you for your hard work! I will try if it works with other c3d files.

**Comment by cadop** [comment]
@lasagnaphil Did this work for you? I would like to close the issue if its working now.

**Comment by lasagnaphil** [comment]
Yes, the c3d loading worked, but unfortunately I wasn't able to test the whole code because we didn't have the VSK skeleton files for the motion capture.

**Comment by cadop** [comment]
Okay thanks for letting me know.  Did you need the vsk for labeling the mocap trial? You don't actually need the VSK to use pyCGM. The only thing it does is load subject measurements from it.
