### ISSUE TITLE
Incorrect Syntax in pyCGM_Single/Pipelines.py

### ISSUE THREAD

**Issue by GVeras** [cadop/pyCGM#23]
Minor incorrect syntax for the function **prep** in **Pipelines.py**.

When running the function prep with correct parameters, the following for loop generates an error:
```
 for key, val in trajs.iteritems():
                temp.update({key:val[i,:]})
```
The specific error raised:
```
    temp.update({key:val[i,:]})
TypeError: list indices must be integers or slices, not tuple
```

It is due to the slice being an incorrect format, instead i think it should just be `temp.update({key:val[i:]})`.
It is also worth noting that it is for both for loops in the function.

**Comment by cadop** [comment]
What is the input you are providing?

**Comment by GVeras** [comment]
I originally provided lists like: `[1,2,3]` and `[[1],[2]]` but upon further testing I came to the conclusion that slicing with `[i,:]` does indeed work, but only with numpy arrays, which does makes sense in the function.
