### ISSUE TITLE
A pycgmStatic.py doctest results in a import math error 

### ISSUE THREAD

**Issue by GVeras** [cadop/pyCGM#26]
When running the command:
 `pytest --doctest-modules --continue-on-collection-errors --ignore=HPC/ --ignore=Muliprocessing/` 
in the main directory, I get the error:
`UNEXPECTED EXCEPTION: NameError("name 'math' is not defined")`
 `R_alpha = np.around(math.degrees(static_info[0][0]*-1),decimals=5)`
`NameError: name 'math' is not defined` 
specifically for a doctest that I created for the function **footJointCenter** in **pycgmStatic.py**. In my doctest I used both `import math` and `from math import *` and neither resolved this issue, even though `import math` should have.

**Comment by cadop** [comment]
This is a problem with your doctest, not the repo.
