### ISSUE TITLE
Setup Workflows

### ISSUE THREAD

**Issue by cadop** [cadop/pyCGM#6]
Setup the github workflows to test pull requests (although kind of needs doc and unit tests first).

**Comment by AdityaJ7** [comment]
I would like to perform pep8 linting in the repo @cadop

**Comment by cadop** [comment]
@AdityaJ7  as mentioned, this issue is for setting up flake8 in actions

**Comment by AdityaJ7** [comment]
Yes.  I would like to work on that

**Comment by AdityaJ7** [comment]
Hey @cadop I was working on the linting but it contains some undefined names

## Here is a screenshot of that
![Error](https://user-images.githubusercontent.com/42397096/94222752-e03c6900-ff0b-11ea-9a83-6c1ee103f81b.PNG)

**Comment by cadop** [comment]
I fixed the C3DData part by removing the main module check as it wasn't used in https://github.com/cadop/pyCGM/commit/6a065e5c67083fc87e1267a9b3826c3d0f456a4d

For the pycgmClusters file, I think its not being used anymore, but honestly not sure if I had integrated all the functions to `clusterCalc.py` or not.  The related functions though are in `pycgmIO.py`.  `JointAngleCalc` is in `pyCGM.py`.  If you could import those to temporarily resolve this issue it would be great.

**Comment by AdityaJ7** [comment]
> I fixed the C3DData part by removing the main module check as it wasn't used in [6a065e5](https://github.com/cadop/pyCGM/commit/6a065e5c67083fc87e1267a9b3826c3d0f456a4d)
> 
> For the pycgmClusters file, I think its not being used anymore, but honestly not sure if I had integrated all the functions to `clusterCalc.py` or not. The related functions though are in `pycgmIO.py`. `JointAngleCalc` is in `pyCGM.py`. If you could import those to temporarily resolve this issue it would be great.

Alright, I will look into that will make the changes by the end of this week
Thanks.

**Comment by cadop** [comment]
workflows are on the dev branch now.  They fail for the above reasons, but these are new issues not really related to setting up workflows.
