### ISSUE TITLE
Existing Docstrings are not in proper Numpy format

### ISSUE THREAD

**Issue by moppr** [cadop/pyCGM#9]
The following functions from each of these files need to have their docstrings reformatted:

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pyCGM.py

- [ ] pelvisJointCenter
- [ ] hipJointCenter
- [ ] hipAxisCenter
- [ ] kneeJointCenter
- [ ] ankleJointCenter
- [ ] footJointCenter
- [ ] headJC
- [ ] thoraxJC
- [ ] findwandmarker
- [ ] findshoulderJC
- [ ] shoulderAxisCalc
- [ ] elbowJointCenter
- [ ] wristJointCenter
- [ ] handJointCenter
- [ ] findJointC
- [ ] cross
- [ ] getPelangle
- [ ] getHeadangle
- [ ] getangle_sho
- [ ] getangle_spi
- [ ] getangle
- [ ] norm2d
- [ ] norm3d
- [ ] normDiv
- [ ] matrixmult 
- [ ] rotmat
- [ ] JointAngleCalc

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgm_embed.py

- [ ] getfilenames
- [ ] loadData
- [ ] main

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmKinetics.py

- [ ] f
- [ ] dot
- [ ] length
- [ ] vector
- [ ] unit
- [ ] distance
- [ ] scale
- [ ] add
- [ ] pnt2line
- [ ] findL5_Pelvis
- [ ] findL5_Thorax

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pyCGM_Helpers.py

- [ ] getfilenames

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/Pipelines.py

- [ ] prep
- [ ] clearMarker
- [ ] filtering

https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmStatic.py

- [ ] rotmat
- [ ] getDist
- [ ] getStatic
- [ ] average
- [ ] IADcalculation
- [ ] staticCalculationHead
- [ ] headoffCalc
- [ ] staticCalculation
- [ ] pelvisJointCenter
- [ ] hipJointCenter
- [ ] hipAxisCenter
- [ ] kneeJointCenter
- [ ] ankleJointCenter
- [ ] footJointCenter
- [ ] headJC
- [ ] uncorrect_footaxis
- [ ] rotaxis_footflat
- [ ] rotaxis_nonfootflat
- [ ] getankleangle
- [ ] findJointC
- [ ] norm2d
- [ ] norm3d
- [ ] normDiv
- [ ] matrixmult 
- [ ] cross

**Comment by GVeras** [comment]
I would like to reformat the strings in pyCGM.py

**Comment by moppr** [comment]
https://github.com/cadop/pyCGM/blob/master/pyCGM_Single/pycgmStatic.py
The following functions from this file need to have their docstrings reformatted:

- [ ] staticCalculation
- [ ] pelvisJointCenter
- [ ] hipJointCenter
- [ ] hipAxisCenter
- [ ] kneeJointCenter
- [ ] ankleJointCenter
- [ ] footJointCenter
- [ ] headJC
- [ ] uncorrect_footaxis
- [ ] rotaxis_footflat
- [ ] rotaxis_nonfootflat
- [ ] getankleangle
- [ ] findJointC
